name: run-lint

on: push

jobs:
  lint-code:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.14.1'
      - run: npm install
      - run: npm run lint
      - run: npm run test:unit

      # run multi-line comand
      - name: Run a multi-line script
        run: |
          echo line one
          echo "line two"
          pwd
          ls ~


