name: run-lint

on: push

jobs:
  lint-code:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      #   uses: actions/setup-node@master

      #   name: Installing project dependencies
      #   run: npm install

        # name: Building the project
        # run: npm run build

      # Runs the Super-Linter action
      # - name: Run Lint
      #   uses: github/super-linter@v3
      #   env:
      #     DEFAULT_BRANCH: main
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}